config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get '/signup', to:'users#new'

  get '/home', to:'static_pages#home'

  get '/help', to:'static_pages#help'
  
  get '/about', to:'static_pages#about'
  
  get '/contact', to:'static_pages#contact'
  
  get 'signup', to:'users#new'
  
  post 'signup', to:'users#create'
  
  get '/login', to: 'sessions#new'
  
  post '/login', to: 'sessions#create'
  
  delete '/logout', to: 'sessions#destroy'
  
  get '/users/delete/:id', to: 'users#destroy', as: 'delete_a_user'
  
  resources :users
  
  root 'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token
    before_save {self.email.downcase!}
    validates :name, presence: true, length: { maximum: 50}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255}, 
         format: { with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
    validates :password, presence: true, length: { minimum: 6}    
    
    has_secure_password
    
    def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
    end
    
    def User.new_token
        SecureRandom.urlsafe_base64
    end
    
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end
    
    def forget
        self.remember_token = nil
        update_attribute(:remember_digest, nil)
    end
    
    def remembered?(remember_token)
        return unless remember_digest
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      if params[:session][:remember_me] == 1
        remember user
      else
        forget user
      end
      redirect_back_or(user_path(user))

    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to home_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :confirm_logged_in, only: [:index, :edit, :update]
  before_action :confirm_access, only: [:edit, :update]
  before_action :confirm_is_admin, only: [:destroy]
  
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(user_param)
    if @user.save
      flash[:success] = "Welcome,#{@user.name}!"
      log_in @user
      remember @user
      
      redirect_to user_url(@user)
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_param)
      flash[:success] = "success to update user information!"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def destroy
    @users = User.find(params[:id])
    if @users && @users.destroy
      flash[:success] = "success to delete user"
      redirect_to users_path
    else
      flash[:danger] = "fail to delete user"
      redirect_to users_path
    end
  end
  
  private
    def user_param
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    
    def confirm_logged_in
      unless log_in?
        store_location
        flash[:danger] = "You should log in first!"
        redirect_to login_path
      end
    end
    
    def confirm_access
      unless params[:id] == current_user.id.to_s
        flash[:danger] = "You have no authority to access that page!"
        redirect_to home_path
      end
    end
    
    def confirm_is_admin
      unless current_user.admin?
        flash[:danger] = "You have no authority to access that page!"
        redirect_to home_path
      end
    end
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def full_title(page_title = '')
        base_title = "Sample Blog use Ruby on Rails"
        if page_title.empty?
            base_title
        else
            page_title + ' | ' + base_title
        end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end
    
    def current_user
        if(user_id = session[:user_id])
            @current_user ||= User.find(user_id)
        elsif (user_id = cookies.signed[:user_id])
            user = User.find(user_id)
            if user && user.remembered?(cookies[:remember_token])
                log_in user
                @current_user = user
            end
        end
    end
    
    def current_user?(user)
       if log_in?
          current_user.id == user.id
       end
    end
    
    def log_in?
        !current_user.nil?
    end
    
    def log_out
        return unless log_in?

        forget @current_user
        @current_user = session[:user_id] = nil
    end
    
    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies[:remember_token] = user.remember_token
    end
    
    def forget(user)
       user.forget
       cookies.delete(:user_id)
       cookies.delete(:remember_token)
    end
    
    def store_location
        session[:forwarding_url] = request.original_url if request.get?
    end
    
    def redirect_back_or(default=home_path)
        redirect_to(session[:forwarding_url] || default)
        session.delete(:forwarding_url)
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = { size: 80})
        gravatar_id = Digest::MD5::hexdigest((user.email).downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{options[:size]}"
        image_tag(gravatar_url, alt: user.name, class:"gravatar")
    end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
        by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
    </small>
    <nav>
        <ul>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <li><a href="http://news.railstutorial.org/">News</a></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
  <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", home_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if log_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li>
            <%= link_to "Log out", logout_path, method: "delete" %>
            </li>
          </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/_userform.html.erb
<%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages'%>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control'%>
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control'%>
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control'%>
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-control'%>
    <%= f.submit "Create my account", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title)%></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    
    
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type%>">
          <%=message%>
        </div>
      <% end %>
      
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
    <%= debug(params) if Rails.env.development? %>
    
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@user.errors.count, "error") %>.
        </div>
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg%></li>
            <% end %>
        </ul>
    </div>
<%end%>

app/views/static_pages/about.html.erb
<% provide(:title, "About")%>

<h1>Test</h1>
<p>this is about page.</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact")%>

<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help")%>

<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home")%>

<div class="center jumbotron">
    <h1>Welcome to the Sample Blog</h1>
    <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
    </h2>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("http://railstutorial-china.org/assets/images/rails.png", alt: "Rails logo"),
'http://rubyonrails.org/' %>

app/views/users/_user.html.erb
<li>
    <%= gravatar_for user, size:50%>
    <%= link_to(user.name,user) %>
    <% if current_user.admin? && !current_user?(user)%>
        <%= link_to " | delete", delete_a_user_path(user), data: { confirm: "Are you sure to delete?"}%>
    <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user information') %>
<h1>Sign up</h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= render 'layouts/userform'%>
    </div>
    <div class="gravatar_edit">
        <%= gravatar_for @user %>
        <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All Users</h1>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
    <%= will_paginate %>
    <ul class="users">
        <%=render @users %>
    </ul>
    <%= will_paginate %>
    </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= render 'layouts/userform'%>
        <p>Already has account? <%= link_to "Login now", login_path%></p>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "#{@user.name} 's blog") %>
<div class="row">
    <aside class="col-md-4">
        <section class="user_info">
            <h1>
                <%= gravatar_for @user%>
                <%= @user.name %>
            </h1>
        </section>
    </aside>
</div>